import {
  movieImg1,
  movieImg2,
  movieImg3,
  movieImg4,
  movieImg5,
  movieImg6,
  movieImg7,
  movieImg8,
  movieImg9,
  movieImg10,
  mainMovie,
} from '../assets';

export const navigation = [
  {
    id: 1,
    link: '/',
    linkName: 'Movies',
    current: true,
  },
  {
    id: 2,
    link: '/tvshows',
    linkName: 'Tv Shows',
    current: false,
  },
  {
    id: 3,
    link: '/animations',
    linkName: 'Animations',
    current: false,
  },
  {
    id: 4,
    link: '/anime',
    linkName: 'Anime',
    current: false,
  },
];

export const genres = [
  {
    id: 1,
    name: 'Action',
  },
  {
    id: 2,
    name: 'Romance',
  },
  {
    id: 3,
    name: 'Comedy',
  },
  {
    id: 4,
    name: 'Sci-fi',
  },
  {
    id: 5,
    name: 'Thriller',
  },
  {
    id: 6,
    name: 'Fantasy',
  },
  {
    id: 7,
    name: 'Adventure',
  },
  {
    id: 8,
    name: 'Horror',
  },
  {
    id: 9,
    name: 'Biography',
  },
  {
    id: 10,
    name: 'Drama',
  },
];

export const movies = [
  {
    id: 1,
    img: mainMovie,
    title: 'Dune',
    year: '2024',
    rating: '8.5',
    genre: 'Adventure, Action',
    watchtime: '2h 15min',
  },
  {
    id: 2,
    img: movieImg6,
    title: 'Indiana Jones',
    year: '2024',
    rating: '7.5',
    genre: 'Adventure, Action',
    watchtime: '2h 15min',
  },
  {
    id: 3,
    img: movieImg7,
    title: 'Spider-Man',
    year: '2024',
    rating: '7.5',
    genre: 'Adventure, Animation, Action',
    watchtime: '2h 15min',
  },
  {
    id: 4,
    img: movieImg8,
    title: 'Elemental',
    year: '2024',
    rating: '7.5',
    genre: 'Adventure, Animation',
    watchtime: '2h 15min',
  },
  {
    id: 5,
    img: movieImg9,
    title: 'No Hard Feelings',
    year: '2024',
    rating: '7.5',
    genre: 'Romance, Comedy',
    watchtime: '2h 15min',
  },
  {
    id: 6,
    img: movieImg10,
    title: 'Transformers',
    year: '2024',
    rating: '7.5',
    genre: 'Adventure, action',
    watchtime: '1h 48min',
  },
  {
    id: 7,
    img: movieImg1,
    title: 'Mario',
    year: '2024',
    rating: '7.5',
    genre: 'Adventure, Animation',
    watchtime: '2h 15min',
  },
  {
    id: 8,
    img: movieImg2,
    title: 'Tomorrow Job',
    year: '2024',
    rating: '7.5',
    genre: 'Adventure, action',
    watchtime: '2h 15min',
  },
  {
    id: 9,
    img: movieImg3,
    title: 'Bridgerton',
    year: '2024',
    rating: '6',
    genre: 'Adventure, action',
    watchtime: '2h 15min',
  },
  {
    id: 10,
    img: movieImg4,
    title: 'Power',
    year: '2024',
    rating: '8.5',
    genre: 'Thriller, Action, Crime',
    watchtime: '1h 05min',
  },
  {
    id: 11,
    img: movieImg5,
    title: 'Scream',
    year: '2024',
    rating: '7.5',
    genre: 'Horror, Thriller',
    watchtime: '2h 15min',
  },
];
